CREATE TABLE `encode`.`encode_formats` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`format_name` VARCHAR(200) NOT NULL COMMENT 'Name of the format (e.g. ipod)', 
	`container` TEXT NOT NULL COMMENT 'name of the container (e.g. mp4)', 
	`video_bitrate` INT NOT NULL COMMENT 'video bitrate (in b/sec)', 
	`video_bitrate_tolerance` INT NOT NULL COMMENT 'video bitrate tolerance (in b/sec)', 
	`video_codec` TEXT NOT NULL COMMENT 'video codec (e.g. libx264)', 
	`video_resolution` TEXT NOT NULL COMMENT 'Video resolution (e.g. 320x180)', 
	`audio_bitrate` INT NOT NULL COMMENT 'audio bitrate (in b/sec)', 
	`audio_samplerate` INT NOT NULL COMMENT 'audio samplerate (in Hz)', 
	`audio_codec` TEXT NOT NULL COMMENT 'audio codec (e.g libfaac)', 
	`vpre_string` TEXT NULL COMMENT 'optional list of -vpre args (e.g. -vpre hq -vpre normal -vpre ipod320)', 
	`aspect_ratio` TEXT NOT NULL COMMENT 'aspect ratio (e.g. 16:9)', 
	`args_beginning` TEXT NULL COMMENT 'optional extra args to put at beginning of command', 
	`args_video` TEXT NULL COMMENT 'optional extra args to put after video options', 
	`args_audio` TEXT NULL COMMENT 'optional extra args to put after audio options', 
	`args_end` TEXT NULL COMMENT 'optional extra args to put at the end', 
	`apply_mp4box` BOOLEAN NOT NULL DEFAULT '0' COMMENT 'Indicates whether the output file should be run through MP4Box. Note this should only be applied to MP4 formats.', 
	`file_extension` VARCHAR(5) NOT NULL COMMENT 'Extension of the resulting file. (e.g. mp4, avi, mov etc). Note this can be different from the container value', 
	`preset_string` TEXT NULL COMMENT 'A preset as understood by ffmpeg (e.g "medium")', 
	`normalise_level` INT NULL COMMENT 'Optional LUFS level to normalise to (e.g -23)', 
UNIQUE (`format_name`)) ENGINE = MyISAM COMMENT = 'Stores ffmpeg options for the Encode Formats for EncodeSrv';

CREATE TABLE `encode`.`encode_jobs` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`source_file` TEXT NOT NULL COMMENT 'Path to source file (e.g. /mnt/UserData/Shows/ManMan/Ep1/10_Man-Man-episode1_sum06.avi)', 
	`destination_file` TEXT NOT NULL COMMENT 'Path to destination file (e.g. /mnt/videos/web/ipod/10_Man-Man-episode1_sum06.mp4)', 
	`format_id` INT NOT NULL COMMENT 'ID to identify format type', 
	`status` VARCHAR(200) NOT NULL DEFAULT 'Not Encoding' COMMENT 'Indicates progress of the encode job. Set to "Not Encoding" initially', 
	`video_id` INT NULL COMMENT 'ID of the relevant video_id. These entires are filled in before the video actaully exists.', 
	`working_directory` TEXT NULL COMMENT 'Stores the working directory once a job has started', 
	`user_id` INT NULL COMMENT 'ID of the user that requested the job', 
	`priority` INT NOT NULL DEFAULT '5' COMMENT 'Mainly for batch encode jobs like re-encodes. Could be used for giving certain events higher priority. Defaults to 5. Higher numbers= lower priority', 
INDEX (`priority`)) ENGINE = MyISAM COMMENT = 'Stores the Encode Jobs for EncodeSrv';